connections:
    - ssh.web-01

remote_folder: "/home/yejianfeng/coredemo/"

frontend:
    pre_action:
        - "pwd"
    post_action:
        - "pwd"

backend:
    goos: linux
    goarch: amd64
    pre_action:
        - "pwd"
    post_action:
        - "chmod 777 /home/yejianfeng/coredemo/hade"
        - "/home/yejianfeng/coredemo/hade app restart"
